name: Hello World script

on: [repository_dispatch]

jobs:
  hello-world-script:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      if: github.event.action == 'script'
      run: .\($env:GITHUB_WORKSPACE)\blob.ps1
